module.exports = {
  API: 'https://api.steemit.com',
  SLEEP_TIME: 15 * 1000,
  BLOCKS_PER_PATCH: 50,
  HISTORY_BLOCKS: 20 * 5, // 5 minutes
  STREAM_FETCHERS_QUEUE: 'STREAM_FETCHERS_QUEUE',
  PAST_FETCHERS_QUEUE: 'PAST_FETCHERS_QUEUE',
  TYPE_VOTE: 'TYPE_VOTE',
  TYPE_TRANSFER_OUT: 'TYPE_TRANSFER_OUT',
  TYPE_TRANSFER_IN: 'TYPE_TRANSFER_IN',
  TYPE_FOLLOW: 'TYPE_FOLLOW',
  TYPE_REBLOG: 'TYPE_REBLOG',
  TYPE_MENTION: 'TYPE_MENTION',
  TYPE_REPLY: 'TYPE_REPLY',
};
